#!/bin/bash
# Removes all generated files, leaving only hand-written source files.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Cleaning..."

# Java bytecode — everywhere in the project
find "$SCRIPT_DIR" -name "*.class" -delete

# ANTLR4-generated Java sources (regenerated by build.sh)
rm -f \
    "$SCRIPT_DIR"/src/SafeLangLexer.java \
    "$SCRIPT_DIR"/src/SafeLangParser.java \
    "$SCRIPT_DIR"/src/SafeLangBaseVisitor.java \
    "$SCRIPT_DIR"/src/SafeLangVisitor.java \
    "$SCRIPT_DIR"/src/SafeLangBaseListener.java \
    "$SCRIPT_DIR"/src/SafeLangListener.java

# ANTLR4 auxiliary files
rm -f \
    "$SCRIPT_DIR"/src/SafeLang.interp \
    "$SCRIPT_DIR"/src/SafeLang.tokens \
    "$SCRIPT_DIR"/src/SafeLangLexer.interp \
    "$SCRIPT_DIR"/src/SafeLangLexer.tokens

# Java sources generated by compile.sh (translated SafeLang programs)
find "$SCRIPT_DIR/examples" -name "*.java" -delete

# Last-compiled record
rm -f "$SCRIPT_DIR/.last_compiled"

echo "Done."
